### ISSUE TITLE
Launchpad S - custom light colours

### ISSUE THREAD

**Issue by ilo-3a29** [monocasual/giada-midimaps#1]
Hi,
would it be possible to have an option for custom light colours for midi output to launchpad S?
Thanks

**Comment by monocasual** [comment]
Sure. I suppose that each color corresponds to a specific MIDI message. You only have to figure it out (it should be documented somewhere in the Launchpad manual) and put it in the right place, e.g.:  

```
  "playing": {
    "channel": 0,
    "message": "<MIDI-message-here>"
  },
```
